---
- hosts: localhost
  become: yes
  gather_facts: no
  tasks:

    - name: Tear down existing services
      community.docker.docker_compose:
        project_src: wordpress-docker
        state: absent

    - name: Create and start services
      community.docker.docker_compose:
        project_src: wordpress-docker
      register: output

    - ansible.builtin.debug:
        var: output

    - name: Run `docker-compose up` again
      community.docker.docker_compose:
        project_src: wordpress-docker
        build: no
      register: output

    - ansible.builtin.debug:
        var: output

    - ansible.builtin.assert:
        that: "not output.changed "

    - name: Stop all services
      community.docker.docker_compose:
        project_src: wordpress-docker
        build: no
        stopped: yes
      register: output

    - ansible.builtin.debug:
        var: output


    - name: Restart services
      community.docker.docker_compose:
        project_src: wordpress-docker
        build: no
        restarted: yes
      register: output

    - ansible.builtin.debug:
        var: output